const users = [
  {
    id: 2,
    entity_id: 1,
    name: 'Himanshu',
    last_name: 'Mohapatra',
    email: 'himanshu.s@us.dynpro.com',
    external_user_id: '102',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 14,
    entity_id: 1,
    name: 'Punit',
    last_name: 'Bopche',
    email: 'punit.bopche@dynpro.com',
    external_user_id: '112',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1003,
    group_name: 'Dynpro_AA',
  },
  {
    id: 17,
    entity_id: 1,
    name: 'Harshada',
    last_name: 'Gorey',
    email: 'harshada.g@us.dynpro.com',
    external_user_id: '114',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 18,
    entity_id: 1,
    name: 'Omkar',
    last_name: 'K',
    email: 'omkar.k@us.dynpro.com',
    external_user_id: '115',
    permissions: 'explorer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1003,
    group_name: 'Dynpro_AA',
  },
  {
    id: 20,
    entity_id: 1,
    name: 'Super',
    last_name: 'Admin',
    email: 'mahesh.bhalchandra@us.dynpro.com',
    external_user_id: '1',
    permissions: 'schedular',
    profile_pic: 'PROFILE-PHOTOS/1637578833_avatar04.png',
    role: 1,
    role_name: 'Super Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 34,
    entity_id: 1,
    name: 'Vikram',
    last_name: 'Jagtap',
    email: 'vikram.jagtap@us.dynpro.com',
    external_user_id: '1',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 35,
    entity_id: 1,
    name: 'Lomash',
    last_name: 'Gautam',
    email: 'lomash.gautam@us.dynpro.com',
    external_user_id: '129',
    permissions: 'explorer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 36,
    entity_id: 1,
    name: 'Prerana',
    last_name: 'Urankar',
    email: 'prerana.urankar@us.dynpro.com',
    external_user_id: '130',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 38,
    entity_id: 1,
    name: 'Vaibhav',
    last_name: 'Dwivedi',
    email: 'vaibhav.dwivedi@us.dynpro.com',
    external_user_id: '132',
    permissions: 'explorer',
    profile_pic: 'PROFILE-PHOTOS/1649846022_images.png',
    role: 1,
    role_name: 'Super Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 39,
    entity_id: 1,
    name: 'Sayali',
    last_name: 'Sonavane',
    email: 'sayali.s@dynproindia.com',
    external_user_id: '133',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1003,
    group_name: 'Dynpro_AA',
  },
  {
    id: 40,
    entity_id: 1,
    name: 'Shivani',
    last_name: 'Waskar',
    email: 'shivani.waskar@us.dynpro.com',
    external_user_id: '134',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1003,
    group_name: 'Dynpro_AA',
  },
  {
    id: 41,
    entity_id: 1,
    name: 'Sharwari',
    last_name: 'Shinde',
    email: 'sharwari.shinde@us.dynpro.com',
    external_user_id: '135',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 50,
    entity_id: 1,
    name: 'Shashikant',
    last_name: 'Karale',
    email: 'shashikant.karale@us.dynpro.com',
    external_user_id: '133',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 83,
    entity_id: 1,
    name: 'Vilas',
    last_name: 'Shinde',
    email: 'vilas.shinde@us.dynpro.com',
    external_user_id: '173',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 88,
    entity_id: 1,
    name: 'm',
    last_name: 'k',
    email: 'mahesh.kapadane@gmail.com',
    external_user_id: '175',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 89,
    entity_id: 1,
    name: 'o',
    last_name: 'p',
    email: 'op@gmail.com',
    external_user_id: '176',
    permissions: 'viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 105,
    entity_id: 1,
    name: 'Nedsaw',
    last_name: 'User',
    email: 'new.user@dynproindia.com',
    external_user_id: '192',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 106,
    entity_id: 1,
    name: 'Nedsaw',
    last_name: 'User',
    email: 'neww.user@dynproindia.com',
    external_user_id: '193',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 108,
    entity_id: 1,
    name: 'sssNew',
    last_name: 'SssUser',
    email: 'sssnew.user13@dynproindia.com',
    external_user_id: '195',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 110,
    entity_id: 1,
    name: 'New',
    last_name: 'User',
    email: 'qnew.user14@dynproindia.com',
    external_user_id: '197',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 111,
    entity_id: 1,
    name: 'fds',
    last_name: 'fsdfdsffs',
    email: 'test1@us.dynpro.com',
    external_user_id: '198',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 112,
    entity_id: 1,
    name: 'fds',
    last_name: 'fsdfdsffs',
    email: 'test2@us.dynpro.com',
    external_user_id: '199',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 113,
    entity_id: 1,
    name: 'fds',
    last_name: 'fsdfdsffs',
    email: 'test3@us.dynpro.com',
    external_user_id: '200',
    permissions: 'explorer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1001,
    group_name: 'Dynpro_SA',
  },
  {
    id: 114,
    entity_id: 1,
    name: 'Test3',
    last_name: 'Tester',
    email: 'tester3@us.dynpro.com',
    external_user_id: '201',
    permissions: 'Viewer',
    profile_pic: null,
    role: 2,
    role_name: 'Account Admin',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 115,
    entity_id: 1,
    name: 'Tester4',
    last_name: 'Test',
    email: 'Tester4@us.dynpro.com',
    external_user_id: '202',
    permissions: 'Viewer',
    profile_pic: null,
    role: 1,
    role_name: 'Super Admin',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 116,
    entity_id: 1,
    name: 'Tester5',
    last_name: 'Test',
    email: 'Tester5@us.dynpro.com',
    external_user_id: '203',
    permissions: 'Viewer',
    profile_pic: null,
    role: 1,
    role_name: 'Super Admin',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 117,
    entity_id: 1,
    name: 'Tester6',
    last_name: 'Test',
    email: 'Tester6@us.dynpro.com',
    external_user_id: '204',
    permissions: 'Viewer',
    profile_pic: null,
    role: 1,
    role_name: 'Super Admin',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 118,
    entity_id: 1,
    name: 'Tester9',
    last_name: 'lastname',
    email: 'Tester9@us.dynpro.com',
    external_user_id: '205',
    permissions: 'Viewer',
    profile_pic: null,
    role: 1,
    role_name: 'Super Admin',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 119,
    entity_id: 1,
    name: 'Test10',
    last_name: 'Tester',
    email: 'tester10@us.dynpro.com',
    external_user_id: '206',
    permissions: 'Explorer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 120,
    entity_id: 1,
    name: 'Tester11',
    last_name: 'fds',
    email: 'tester11@us.dynpro.com',
    external_user_id: '207',
    permissions: 'Viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
  {
    id: 121,
    entity_id: 1,
    name: 'Tester12',
    last_name: 'fadsjkl',
    email: 'testser12@us.dynpro.com',
    external_user_id: '208',
    permissions: 'Viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1003,
    group_name: 'Dynpro_AA',
  },
  {
    id: 122,
    entity_id: 1,
    name: 'John ',
    last_name: 'Doe',
    email: 'johndoe11@us.dynpro.com',
    external_user_id: '209',
    permissions: 'Viewer',
    profile_pic: null,
    role: 3,
    role_name: 'User Viewer',
    user_group_id: 1011,
    group_name: 'Dynpro_Viewer',
  },
];

export default users;
