const serverIp = '44.199.193.239';
// const baseURL = 'http://192.168.1.239/api';
const baseURL = 'http://127.0.0.1:8000/api';

const commonConfig = {
  tokens: {
    persist: 'persist:root',
    accessToken: 'accessToken',
    lastScheduledTime: 'lastScheduledTime',
  },

  navTextColor: {
    level0: '#3a80ec',
    level1: '#bcf5f9',
    level2: '#89c5fd',
    level3: '#ffffff',
  },
  urls: {
    baseURL,
    login: `${baseURL}/login`,
    logout: `${baseURL}/logout`,
    refreshToken: `${baseURL}/refresh`,
    register: `${baseURL}/register`,
    validateOtp: `${baseURL}/validate_otp`,
    resendOtp: `${baseURL}/resend_otp`,
    forgotPassword: `${baseURL}/resend_otp`,
    forgetPasswordChange: `${baseURL}/forget_password_change`,
    forget_password: `${baseURL}/forget_password`,
    getClientsUrl: `${baseURL}/getLookerClient`,
    getFoldersUrl: `${baseURL}/getLookerClientFolder`,
    getDashboardsUrl: `${baseURL}/getLookerFolderDashboard`,
    getLookerDashboard: `${baseURL}/getDashboard`,
    getLookerClientCategoryWiseAll: `${baseURL}/getLookerClientCategoryWise`,
    getLookerClientCategoryWiseUserAccess: `${baseURL}/clientCateWiseUserAccess`,
    getLookerClientCategoryWiseAllNew: `${baseURL}/getLookerClientCategoryWiseNew`,
    getClientCateWiseUserAccesAllsNew: `${baseURL}/clientCateWiseUserAccessNew`,
    getClientCategory: `${baseURL}/get_clientCategory`,
    getSubCategory: `${baseURL}/get_subcategory`,
    getUserAccessClients: `${baseURL}/getUserAccessClients`,
    getUserAccessFolders: `${baseURL}/getUserAccessFolders`,
    getUserAccessdashboards: `${baseURL}/getUserAccessdashboards`,
    user: `${baseURL}/user`,
    groupRoleMapping: `${baseURL}/group_role_mapping`, // followed by grpId /grpid
    groups: `${baseURL}/groups`,
    groupList: `${baseURL}/grouplist`,
    roles: `${baseURL}/roles`,
    getUserList: `${baseURL}/user`,
    getUser: `${baseURL}/user`,
    createUser: `${baseURL}/user`,
    getGroups: `${baseURL}/groups`,
    getGroupRoleMapping: `${baseURL}/group_role_mapping`, // followed by grpId /grpid
    role: `${baseURL}/roles`,
    getRole: `${baseURL}/roles`,
    getRoleList: `${baseURL}/roles`,
    createRole: `${baseURL}/roles`,
    getclientList: `${baseURL}/clients`,
    client: `${baseURL}/clients`,
    createClient: `${baseURL}/clients`,
    updateClient: `${baseURL}/client_update`,
    getlookerfolderStructure: `${baseURL}/getLookerFolderStructure`,
    getparentphm: `${baseURL}/getParentPHM`,
    getschema: `${baseURL}/getSchema`,
    getlookerGroups: `${baseURL}/getLookerGroups`,
    getUserAccessControl: `${baseURL}/useraccess`,
    getGroupRoleUser: `${baseURL}/getGroupRoleUser`,
    looker: `${baseURL}/looker`,
    inviteUser: `${baseURL}/invite_user`,
    phmAutomationReportList: `${baseURL}/phm_automation_report_list`,
    phmAutomationClientList: `${baseURL}/phm_automation_client_list`,
    phmAutomationYearList: `${baseURL}/phm_automation_year_list`,
    phmAutomationStoreReportRequest: `${baseURL}/phm_automation_store`,
    phmAutomationDeleteReportRequest: `${baseURL}/phm_automation_destroy`,
    phmAutomationDownloadReport: `${baseURL}/phm_automation_download`,
    psAutomationReportList: `${baseURL}/ps_automation_report_list`,
    psAutomationClientList: `${baseURL}/ps_automation_client_list`,
    psAutomationCreatePatientList: `${baseURL}/ps_automation_patient_list`,
    psAutomationViewPatientList: `${baseURL}/ps_automation_listof_patient`,
    psAutomationStoreReportRequest: `${baseURL}/ps_automation_store`,
    psAutomationDeleteReportRequest: `${baseURL}/ps_automation_destroy`,
    psAutomationDownloadReport: `${baseURL}/ps_automation_download_zip`,
    localizedClients: `${baseURL}/localized_clients`,
    localizedPHMClients: `${baseURL}/localized_phm_clients`,
    localizedDashboards: `${baseURL}/localized_all_dashboards`,
    pullLookerClients: `${baseURL}/pull_looker_clients`,
    pullLookerPHMFolders: `${baseURL}/pull_looker_phmfolders`,
    pullLookerDashboards: `${baseURL}/pull_looker_dashboards`,
    getUserProfile: `${baseURL}/profile`,
    updateUserProfile: `${baseURL}/profile_update`,
    getInTouch: `${baseURL}/get_in_touch`,
    getEmployeeList: `${baseURL}/employee`,
    employee: `${baseURL}/employee`,
  },
};

export default commonConfig;
